// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkwieqexvemtnfdoaiim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrd2llcWV4dmVtdG5mZG9haWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzgwNjAsImV4cCI6MjA2NzkxNDA2MH0.CP59TkWoolRLcCeR2FjapDSTk3zLy4ZnHOFEE1TJSO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});